### ISSUE TITLE
Testing images, not training images!

### ISSUE THREAD

**Issue by Z863058** [irfanICMLL/CoupleGenerator#8]
"Download the training images and unzip it: https://cloudstor.aarnet.edu.au/plus/s/VWZJaWfbla3kFch"
but they are testing images, not training images!

**Comment by irfanICMLL** [comment]
Sorry for the name of the folder.
This is a toy model. We only have 157 training pairs. I have already said that the model can fit training data in a short time, but the generalization ability is limited due to the small dataset. If you want to make an effective model, you can collect more data.
I have provided the spyder I use, which is very simple. We also employ a face detection tool to extract faces from the collecting images.

Good luck.
